// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lehcvgwwnymcqgsllfmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxlaGN2Z3d3bnltY3Fnc2xsZm1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMDc3MzUsImV4cCI6MjA2Mzg4MzczNX0.uv_TwYDYvdSqIxwnBZTwjr2cQcm3ABMIvUR4JW_9wZc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);